### ISSUE TITLE
Evaluate Rocket Chat instead of Slack

### ISSUE THREAD

**Issue by plfiorini** [lirios/lirios#16]
It's Open Source and self hosted: https://rocket.chat/

**Comment by oKcerG** [comment]
What about Mattermost ? open source and self hosted too https://www.mattermost.org/

**Comment by crutchcorn** [comment]
Why again? I like yelling at everyone on a platform I already use

**Comment by tim-sueberkrueb** [comment]
+1 for using a self-hosted open-source solution if we can afford it.

**Comment by Aldrog** [comment]
I see no reason to switch. Slack is reliable, feature-full and doesn't conduct any campaign against third-party clients. For me that's enough to stick to it.

**Comment by oKcerG** [comment]
Switching to a self-hosted solution will add cost and workload.
And I believe Slack is far more widely used than Rocket Chat, so @crutchcorn's reason doesn't really work here.

**Comment by crutchcorn** [comment]
@oKcerG I was talking about Slack. So, my reasoning does really work here ;)

**Comment by oKcerG** [comment]
I misunderstood the Why again :) and the digging up of this old issue.
