### ISSUE TITLE
Qt Virtual Keyboard?

### ISSUE THREAD

**Issue by kq01526** [lirios/lirios#21]
@plfiorini :

If I understand it correctly, you had added Qt Virtual Keyboard to Hawaii:

http://plfiorini.blogspot.com/2016/04/qt-virtual-keyboard-support-on-hawaii.html
https://github.com/hawaii-desktop/hawaii-shell/issues/219
https://github.com/greenisland/greenisland/issues/193
https://github.com/hawaii-desktop/hawaii-workspace/issues/4
https://github.com/hawaii-desktop/hawaii-system-preferences/issues/39

When I boot **lirios-2017.01.12.iso** , I can see a setting to enable virtual keyboard input source, but when it is enabled, Qt Virtual Keyboard still doesn't show up.

Do you know why? How can I make Qt Virtual Keyboard show up?

Regards

**Comment by plfiorini** [comment]
It should still support it although TBH I haven't used it in a while so I will check if it is still working.
The main problem is that once you enable the virtual keyboard from Settings you need to restart the desktop, the setting is being picked up at startup because it's a Qt env var.

**Comment by plfiorini** [comment]
@kq01526 It works except for an issue with the applications menu being a modal dialog when you click on the virtual keyboard it will dismiss the dialog.
Filing a specific issue: https://github.com/lirios/shell/issues/77

**Comment by plfiorini** [comment]
And https://github.com/lirios/shell/issues/78

**Comment by kq01526** [comment]
> @plfiorini 
> The main problem though is that once you enable the virtual keyboard from Settings you need to restart the desktop

Is it possible to do that from the live ISO?

**Comment by plfiorini** [comment]
@kq01526 Yes it can, you don't need to reboot the system just logout and login again. Unfortunately it's an environment variable that needs to be read at startup.
