### ISSUE TITLE
Could not open configuration file "/root/.config/liri/platform.json" for reading

### ISSUE THREAD

**Issue by FeniixDev** [lirios/lirios#27]
### Can you help me please ?

https://gyazo.com/d3b17e93d9bcf7f021f9123e36a18c3d

> liri.qpa.deviceintegration: EGL device integration plugin lookup paths: /usr/lib/qt/plugins /usr/bin
> liri.qpa.deviceintegration: Preferred EGL device integration based on the hardware configuration: "kms"
> liri.qpa.deviceintegration: Using "kms" EGL device integration
> liri.qpa.kms: Loading configuration from "/home/ben/.config/liri/platform.json"
> liri.qpa.kms: Could not open configuration file "/home/ben/.config/liri/platform.json" for reading
> liri.qpa.deviceintegration: logind connection not yet established
> liri.qpa.logind: Session path: "/org/freedesktop/login1/session/c2"
> liri.qpa.deviceintegration: Take control of session via logind
> liri.qpa.logind: Acquired control of the session
> liri.qpa.deviceintegration: Initialization
> liri.qpa.kms: Found the following video devices:
> liri.qpa.kms: 	 /dev/dri/card0
> liri.qpa.kms: Using autodetected "/dev/dri/card0"
> liri.qpa.kms: Opening device "/dev/dri/card0"
> liri.qpa.kms: Creating GBM device for file descriptor 12 obtained from "/dev/dri/card0"
> Erreur de segmentation
>

**Comment by plfiorini** [comment]
Could not open error is not a problem since the file is created the first time the session is closed.
The problem here is the segfault, @FeniixDev did you use the Arch Linux package from the liri-unstable repo? If that is the case could you check again, there was a bug in Fluid that made the desktop crash that is now fixed.

**Comment by FeniixDev** [comment]
It does not work :/

**Comment by FeniixDev** [comment]
I have the "settings.json" of liri-browser but not that of liri

https://screencloud.net/v/q1uA

**Comment by plfiorini** [comment]
0. Missing settings file is not a problem
1. Upgrade with `pacman -Syu`
2. Log in as user in a text console (outside any desktop environment) there is no reason to use root
3. Don't run liri-session with sudo, the environment will not be set correctly
4. Enable more verbose log messages, edit ~/.config/QtProject/qtlogging.ini and add:
```
[Rules]
*.warning=true
*.error=true
liri.*=true
vibe.*=false
```
5. As user from a text console (outside any desktop environment) type: `liri-session &> log`

See if it still crashes, in case it does paste the file called `log` here.

**Comment by sandeshbhusal** [comment]
I have the same problem :(

**Comment by plfiorini** [comment]
This should be fixed now!
