### ISSUE TITLE
hardware - rasp pi 3 with touch screen

### ISSUE THREAD

**Issue by gedw99** [lirios/lirios#32]
I knwo its early days, but i want to try out running the OS on a rasp.

Can someone tell me if this is intended use case and if the base OS has been designed for ARM ?

**Comment by Collinthegeek** [comment]
See #24 
Please check to see if your question has already been asked before submitting a new issue.

**Comment by gedw99** [comment]
thanks i missed it on my initial search because the other dude used RPI to describe it:)
