### ISSUE TITLE
password in usb live

### ISSUE THREAD

**Issue by foozzi** [lirios/lirios#33]
What is default password for Live User in usb?? I now use virtual machines

**Comment by Collinthegeek** [comment]
See #30 
Please check to see if your question has already been asked before submitting a new issue.

**Comment by plfiorini** [comment]
Live media doesn't have passwords (neither `root` nor `liveuser`).
There are two possible issues here: you are either using Virtualbox that doesn't support Wayland properly or, most likely, hit a regression caused by libglvnd which is fixed in today ISO.
