### ISSUE TITLE
Black screen on install

### ISSUE THREAD

**Issue by Collinthegeek** [lirios/lirios#35]
I installed from the latest image with Calemeres and on reboot I just see a cursor blinking in the top left. No grub. I crooted into it from the livecd and grub appears to be configured properly. Any ideas?

**Comment by Collinthegeek** [comment]
Fixed, toggled the boot flag with parted.

**Comment by plfiorini** [comment]
BTW I've seen the IRC log through Slack: the installer is Calamares, a distro-indipendent installer written with Qt (https://github.com/calamares).

**Comment by plfiorini** [comment]
Almost forgot: the installer is customizable and configurable.
Liri OS config files are here: https://github.com/lirios/calamares-branding
