### ISSUE TITLE
liri-session ptint issue and not start

### ISSUE THREAD

**Issue by 115Prometey** [lirios/lirios#38]
Liri shell not starts on my PC. I'm install fresh Arch Linux (build of 2017-04-01) and append OS of UI. Install sddm, xfce4, liri from official repository. Xfce4 starts normaly. Liri not started. After chosing "Liri (wayland)" from drop box of sddm and user logining, I see black screen and system reload sddm.service and reshow sddm ligining activity. Next my step is disable sddm.service of "_$ systemctl disable sddm.service_". Reboot OS. Logining user on OS in tty terminal. Execute command without arguments "_$ liri-session_" and this print me issue message:

_"**/bin/liri-shell: relocationerror: /usr/lib/libLiriWaylandServer.so.0: symbol wl_surface_interface? version Qt_5 not defined in file libQtWaylandCompositor.so.5 with link time reference**"_

I'm reinstall liri packages by command "_$ sudo pacman -Rs liri-shell-git liri-settings-git liri-terminal-git liri-files-git liri-appcenter-git_" and "_$ sudo pacman -S liri-shell-git liri-settings-git liri-terminal-git liri-files-git liri-appcenter-git_".  this has same effect. It's no work. Liri-session print same issue.

My OS location and timezone is **Europe/Kiev**. My PC: "**Acer Aspiri 5742g–384g50mncc**". Installed video driver: **xf86-video-ati**

**Comment by 115Prometey** [comment]
Pier, what about my question? It's my bug in installation an configuration Arch or no? What I cen do for install LIRI  for long using?

**Comment by plfiorini** [comment]
Can't reproduce it in the live image, can you `pacman -Syu` and see if it happens again?

**Comment by 115Prometey** [comment]
Yea! after update it's work!! I happy!:) But liri shell has an invisible mouse cursor!!! Bug of previos liri live iso!!!

**Comment by plfiorini** [comment]
yeah i will take a look, i couldn't reproduce it on my installed PC. how do you run the shell, from tty, gdm, sddm or what?

**Comment by joksik** [comment]
i remember that @115Prometey was write on liri google++ that he use sddm

**Comment by 115Prometey** [comment]
I'm run liri session from sddm

**Comment by plfiorini** [comment]
sddm saves the log of wayland sessions here: `~/.local/share/sddm/wayland-session.log` can you put it somewhere like pastebin.com ?

**Comment by 115Prometey** [comment]
I will put this file on my google disk and will share it. After I send referance on it in this comment. But I can make it tomorrow. Liri on my home PC. home PC without internet. Thank you for seen my question)

**Comment by 115Prometey** [comment]
This is a link on the _wayland-sessio.log_ file on google drive.
https://drive.google.com/file/d/0By_cO7WBEIigb3RCUWRhQnd4Q1E/view?usp=sharing

**Comment by plfiorini** [comment]
I don't see the shell helper running that's the problem. Pretty sure something is wrong with the paths, maybe caused by some mistake made in the new qbs build system rules.

**Comment by 115Prometey** [comment]
Ок. I will try reinstall Arch and Liri

**Comment by plfiorini** [comment]
There's no need, first I have to check what's wrong with the package

**Comment by hughwilliams94** [comment]
Just to say that I have encountered this same issue. I love the look of this OS though keep up the excellent work.

**Comment by 115Prometey** [comment]
I'm reinstall my Arch at clean and reinstall all liri packages. Issue not gone

**Comment by joksik** [comment]
its must be very dirty bug, because we have 2 weeks later and it is still not fixed :/

**Comment by 115Prometey** [comment]
The mouse cursor is present, but is invisible. I drag mouse at a left buttom corner, and I see glow of cursor. After I drag an invisible mouse no more to right at the "terminal louncher icon", "terminal louncher icon" begin obscured an has reaction on mouse left button click. If I lounch some application frame (for example: "eclipse") the mouse cursor appears on app frame and go to the invisible state after I drug mouse out of app frame.

**Comment by plfiorini** [comment]
Reproduced, I blame XWayland:

```
liri.xwayland: Xwayland started on display :1
[658809.549] wl_seat@3.get_pointer(new id wl_pointer@13)
[658809.577] wl_pointer@13.set_cursor(0, nil, 0, 0)
[658809.606]  -> wl_surface@17.leave(wl_output@15)
```

Seems like it unsets the cursor.

**Comment by plfiorini** [comment]
Tracked in https://github.com/lirios/shell/issues/106

**Comment by plfiorini** [comment]
New snapshot seems fixed [1] with VMware

[1] https://repo.liri.io/images/nightly/lirios-2017.07.03.iso
