### ISSUE TITLE
Terminal app doesn't work

### ISSUE THREAD

**Issue by dossalab** [lirios/lirios#42]
[roman@dossalab ~]$ liri-terminal
Using Wayland-EGL
Pass a valid window to KWallet::Wallet::openWallet().
Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.Spawn.ChildSignaled", "Process org.kde.kwalletd5 received signal 6")
The kwalletd service is still not registered
Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.Spawn.ChildSignaled", "Process org.kde.kwalletd5 received signal 6")
The kwalletd service is still not registered
Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.Spawn.ChildSignaled", "Process org.kde.kwalletd5 received signal 6")
The kwalletd service is still not registered
Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.Spawn.ChildSignaled", "Process org.kde.kwalletd5 received signal 6")
The kwalletd service is still not registered
Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.Spawn.ChildSignaled", "Process org.kde.kwalletd5 received signal 6")
The kwalletd service is still not registered
Couldn't start kwalletd:  QDBusError("org.freedesktop.DBus.Error.Spawn.ChildSignaled", "Process org.kde.kwalletd5 received signal 6")
The kwalletd service is still not registered
Invalid DBus reply:  QDBusError("org.freedesktop.DBus.Error.Spawn.ChildSignaled", "Process org.kde.kwalletd5 received signal 6")
ASSERT: "m_wallet != nullptr" in file /build/src/vibe/declarative/wallet/kquickwallet.cpp, line 41
Aborted (core dumped)

**Comment by xCuri0** [comment]
Installing `kdebase-runtime` and running `kdebase-runtime` in a terminal fixed it for me

**Comment by plfiorini** [comment]
Fixed
