### ISSUE TITLE
Can't start Liri

### ISSUE THREAD

**Issue by hughwilliams94** [lirios/lirios#44]
On an Arch Linux install using the latest packages from your repo, I cannot login to liri I simply get kicked back to sddm. If I switch to a tty and try to run liri-shell manually I simply get a segmentation fault.

If I look at journalctl -xe I see that the segfault is occurring in libLiriUDev.so.0.0.0

**Comment by plfiorini** [comment]
I'm making a VM to debug the issue.

**Comment by plfiorini** [comment]
It's an heisenbug, no longer reproduced with the last iso image.

**Comment by plfiorini** [comment]
Found and fixed, but you won't see it fixed until I trigger a package rebuild.

**Comment by hughwilliams94** [comment]
Great thanks, will try it once the package gets rebuilt!

**Comment by plfiorini** [comment]
Packages updated.

Tests done:

* Several attempts on the development PC: zero crashes
* Last ISO boot on VMware: no crash
* Update of an installed virtual machine: no crash

**Comment by itay-grudev** [comment]
I currently have the same issue, but `journalctl -xe` is a bit cryptic and I can't tell exactly what's causing the issue. Is there a _debuging_ or _verbosity_ flag?

**Comment by itay-grudev** [comment]
This error sometimes appears (though I'm never able to start lirios) on Arch:

```
cannot mix incompatible qt library (version 0x50a01) with this library (version 0x50b01)
```

**Comment by maenpaa24** [comment]
so am I. Both experiencing the error and on arch.
