### ISSUE TITLE
Mark papyros as deprecated

### ISSUE THREAD

**Issue by Cl1608Ho** [lirios/lirios#46]
Do the stuff like you did with hawaii

- [ ] Mark Github organization/repo(s) as deprecated and link to lirios
- [x] Mark [papyros.io](http://papyros.io/) as deprecated and link to lirios
- [ ] Take over bountysource project / refer to lirios.
- [ ] Maybe, if its possible, take over any funds that were left on papyros (as I'm seeing right now, we still got $60 bounties)

did i miss anything?

**Comment by plfiorini** [comment]
Only @iBelieve has access to those things and has already been emailed about it but hasn't replied. Maybe he's been busy but he will read this message.
