### ISSUE TITLE
Use this repo as a superbuild to checkout and build all projects

### ISSUE THREAD

**Issue by iBelieve** [lirios/lirios#5]
Like https://github.com/lxde/lxqt

**Comment by plfiorini** [comment]
@iBeliever what about using repo manifest like https://github.com/hawaii-desktop/hawaii (still in this repo)?

**Comment by plfiorini** [comment]
i was using git submodules back then but it's difficult to keep track of the right submodule revision and requires extra maintainance (checkout the last revision and commit)

**Comment by iBeliever** [comment]
I haven't seen that repo tool, but it looks nicer than using submodules, so it's fine by me. The main thing I'd like to see is just a way to get all the repos and build from one CMake config like lxqt is doing.

**Comment by plfiorini** [comment]
that would be cool i can try

**Comment by plfiorini** [comment]
Done, needs testing.

**Comment by plfiorini** [comment]
Done, with Qbs!
