### ISSUE TITLE
How to solve the "bad source" prompting when installing

### ISSUE THREAD

**Issue by jiqing112** [lirios/lirios#56]
![arch-2018-05-20-12-52-07](https://user-images.githubusercontent.com/17674011/40276099-9e2d32c4-5c33-11e8-85ee-f7a8c6ca49f2.png)

**Comment by jiqing112** [comment]
![arch-2018-05-20-13-43-32](https://user-images.githubusercontent.com/17674011/40276109-ce495744-5c33-11e8-974d-ab64dd13321e.png)

**Comment by nagualcode** [comment]
manual fix?

**Comment by plfiorini** [comment]
This doesn't happen for a while now.
Now, instead of rsyncing the live image into the installation root, the installer deploys OSTree.
