### ISSUE TITLE
docker image fails: xcb missing

### ISSUE THREAD

**Issue by mviereck** [lirios/lirios#57]
I tried the docker  image [`lirios/unstable`](https://hub.docker.com/r/lirios/unstable/). It fails with error message:
```
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
```

**Comment by plfiorini** [comment]
Looks like it might be a Qt issue, used to work before may. Other people are experiencing it and the same issue happens with both Arch Linux and Fedora 28.
Move the issue to the specific repository: https://github.com/lirios/docker-lirios/issues/1
