### ISSUE TITLE
qbs is being retired in favor of CMake

### ISSUE THREAD

**Issue by Conan-Kudo** [lirios/lirios#60]
The Qt Company has decided to [stop development of Qbs and migrate to CMake](http://blog.qt.io/blog/2018/10/29/deprecation-of-qbs/).

As Liri OS uses Qbs for building its software, it'll want to start moving before it's fully retired next year.

**Comment by plfiorini** [comment]
Yeah I read it. I still need to recover myself :(
Hopefully they will address some CMake shortcomings and improve QtCreator integration even further.

First step is to add CMake to all Liri projects, keeping Qbs and qmake where they are.
Second step, once QtCreator integration can compete with Qbs, is to stop supporting the Qbs build system. Qmake will still be supported in Fluid for a while (along side CMake).

**Comment by plfiorini** [comment]
Work has started in the `feature/cmake` branch of each project.

**Comment by plfiorini** [comment]
BTW here's the mailing list post: http://lists.qt-project.org/pipermail/development/2018-October/034023.html

**Comment by plfiorini** [comment]
Done!
