### ISSUE TITLE
Add output in the installer

### ISSUE THREAD

**Issue by bretantonio** [lirios/lirios#63]
Please I would like to see what the installer is doing. It can stay at 22% for 1hour leaving me to wonder if something is wrong

**Comment by plfiorini** [comment]
Right now the installer downloads the OS bits from the Internet and that takes time (it depends on how fast is the network, server and disk write speed).  In the near feature I want to see if the OSTree repository can fit the ISO, making it way faster to install.
Meanwhile you can check the logs in  `~/.cache/Calamares/Calamares.log`
