### ISSUE TITLE
liri-session not launch

### ISSUE THREAD

**Issue by illvart** [lirios/lirios#68]
I trying again to install liri by use Arch Linux wiki [here](https://wiki.archlinux.org/index.php/Liri), but liri-session not launch.

Error:
```
Failed to create wl_display (Connection refused)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: liri, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

[1]    2654 abort      liri-session -platform wayland

```

**Comment by plfiorini** [comment]
Are you sure you are running this in your Wayland session?

What does `$WAYLAND_DISPLAY` contains?

What is the output of `liri-session -platform wayland` when you `export WAYLAND_DEBUG=1` before running it?

**Comment by plfiorini** [comment]
In a console `XDG_SESSION_TYPE=tty` now instead of being empty, so the algorithm choose `wayland` and `xcb`.
The `wayland` QPA plugin obviously fails because it cannot connect to a display and so is true for the X11 display.
