### ISSUE TITLE
Live ISO: No login prompt

### ISSUE THREAD

**Issue by ToxicDragon** [lirios/lirios#69]
In the current live ISO (14.01.2020) there is no prompt for signing into the session. I am stuck on the screen where I can choose the compositor or shutdown (right bottom corner)

**Comment by plfiorini** [comment]
The user gets created at runtime, it means [live-system-setup.service](https://github.com/lirios/ostree-config/blob/develop/overlay.d/05live/usr/lib/systemd/system/live-system-setup.service) fails.
I download the 14/01/2020 ISO and see for myself.

**Comment by plfiorini** [comment]
The problem is with `sysroot-etc.mount`, that makes /etc writable.
Says "Failed with result 'protocol'"

**Comment by ToxicDragon** [comment]
Can you fix this?

**Comment by plfiorini** [comment]
I think it's related to: https://github.com/systemd/systemd/issues/10872

**Comment by plfiorini** [comment]
Fedora CoreOS (of which Liri OS has many similarities) have the same problem: https://github.com/coreos/fedora-coreos-tracker/issues/363

But this is blocking to us since the user is created during the boot and needs to access /etc.

This wasn't happening about 1 month ago.

**Comment by plfiorini** [comment]
@ToxicDragon I'm trying to do a workaround, a service unit that manually mounts /sysroot/etc

**Comment by plfiorini** [comment]
Workaround seems to work:
![Screenshot from 2020-02-01 16-15-53](https://user-images.githubusercontent.com/843710/73594366-2a508480-450e-11ea-94c7-ca29872a1534.png)

**Comment by ToxicDragon** [comment]
Nice, thx! I'll give it a try once I'm back home

**Comment by plfiorini** [comment]
I'll tell you when new images start to get the fix. That was a local build.

**Comment by plfiorini** [comment]
The workaround works. I struggled with an orthogonal issue, fixed [with this commit](https://github.com/lirios/image-config/commit/5a20256b4e11cfba92039f6539925ba631c12dcc) that's why I had it working on local builds but it wasn't working with server builds.

Todays build (05/02/2020) works, tested in two computers, but there is an issue with the installer.
Now images are completely based on OSTree and there is probably something to fix with the installer.

**Comment by ToxicDragon** [comment]
I confirm that you workaround seems to fix the problem (just tested with the latest iso)

What I thought back then and I still think nowadays: Liri is such a great DE and has so much potential! Would be great to more progress and maybe also more activity in social meda about it (e.g. twitter)! Once https://github.com/johanhelsing/qt-csd-demo and the corresponding features work, it would be sooo nice to see CSD finally coming!
