### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by luka177** [lirios/lirios#77]
## Expected Behavior
Liri-shell must start

## Current Behavior

It crashes 
```
== Liri Session ==
** https://liri.io
** Bug reports to: https://github.com/lirios/session/issues
** Build: 0.1.0-tarball
OS: Fedora 32 (Thirty Two) [linux version 4.4.146+]
Architecture: arm64
liri.session: ==> Starting session module "io.liri.SessionManager.Modules.Shell"
liri.session: Trying to run liri-shell...
/usr/libexec/liri/liri-shell: symbol lookup error: /usr/libexec/liri/liri-shell: undefined symbol: _ZN29QWaylandQuickShellSurfaceItem14mouseMoveEventEP11QMouseEvent, version Qt_5
liri.session: "/usr/libexec/liri/liri-shell" finished with exit code 127
liri.session: Failed to start session module "io.liri.SessionManager.Modules.Shell"
liri.session: Closing session...
liri.session: Quit

```

## Steps to Reproduce (for bugs only)

1.Get fedora 32 aarch64
2.sudo dnf copr enable plfiorini/liri-nightly
3.sudo dnf install -y \
    liri-networkmanager \
    liri-platformtheme \
    liri-power-manager \
    liri-pulseaudio \
    liri-screencast \
    liri-screenshot \
    liri-settings \
    liri-shell \
    liri-wallpapers \
    qml-xwayland \
    xdg-desktop-portal-liri \
    paper-icon-theme \
    liri-color-schemes
4.dbus-run-session liri-session --no-systemd

## Environment

Include as many relevant details about the environment you experienced the bug in.

* Version used: lastest from plfiorini/liri-nightly
* Operating system and version: Fedora 32 aarch64
* Device (phone, tablet, laptop, desktop, ...): phone
* CPU, RAM, screen resolution: Mediatek mt6763, 4GB RAM

**Comment by plfiorini** [comment]
As said on the chat a few days ago, the problem is caused by Qt removing a symbol in a non retrocompatible way.
Rebuilding `liri-shell` and `liri-wayland` fixed the issue.
